version: '3'

services:
  web:
    image: "web:latest"
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment: 
      FLASK_APP: app/app.py
    
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    